### model
model_name_or_path: Qwen/Qwen2-VL-7B-Instruct

### method
stage: sft
do_train: true
finetuning_type: full
deepspeed: examples/deepspeed/ds_z0_config.json

### dataset
dataset: mire_train  # video: mllm_video_demo
template: qwen2_vl
cutoff_len: 1024
max_samples: 10000
overwrite_cache: true
preprocessing_num_workers: 16
val_size: 0.1

### output
output_dir: saves/qwen2_vl-7b/full/sft
logging_steps: 1
save_steps: 0.2
plot_loss: true
overwrite_output_dir: true

### train
per_device_train_batch_size: 2
gradient_accumulation_steps: 2
learning_rate: 5.0e-6
num_train_epochs: 3.0
lr_scheduler_type: cosine
warmup_ratio: 0.05
fp16: true
ddp_timeout: 180000000

### eval
val_size: 0.1
per_device_eval_batch_size: 8
eval_strategy: steps
eval_steps: 5

flash_attn: fa2
deepspeed: examples/deepspeed/ds_z3_offload_config.json
